### ISSUE TITLE
Does not properly parse when using \n without \r\n

### ISSUE THREAD

**Issue by Wixred** [bvanderveen/httpmachine#14]
If lines in a HTTP request or HTTP response does not have a carriage return, the parser fails to parse the full request/response.

**Comment by bvanderveen** [comment]
Hi there, thanks for your interest in HttpMachine! For what it's worth,
'\r\n' (CRLF) is required per RFC 2616.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4

Best regards,
Benjamin
503 719 3578
