### ISSUE TITLE
Add license.

### ISSUE THREAD

**Issue by txdv** [bvanderveen/httpmachine#9]
Could you please license your code under MIT.

Without a license I can't reuse any of your code.

**Comment by bvanderveen** [comment]
It is already licensed under MIT.

**Comment by txdv** [comment]
I am sorry, I didn't see the License in the Readme file so I assumed it didn't exist.

It would be nice to mention to license in the readme file.

**Comment by bvanderveen** [comment]
The readme does mention the license.
